# DNS profile transformation; never changes network policy or user groups.
module OpenKillDnsPrivacy
  BOOTSTRAP = ['https://1.1.1.1/dns-query', 'https://223.5.5.5/dns-query'].freeze

  # Mihomo accepts one routing selector after `#` (a proxy/group name,
  # interface name or RULES) followed by connection parameters.  Strict mode
  # owns that selector: it replaces an internally generated RULES selector
  # with the dedicated DNS group, preserves safe connection parameters, and
  # rejects a user-provided competing selector instead of silently changing
  # where DNS is sent.
  SAFE_PARAMETERS = /\A(?:h3|disable-ipv4|disable-ipv6|disable-reuse|disable-qtype-[0-9]+)=(?:true|false)\z/i

  def self.parts(server)
    text = server.to_s
    raise ArgumentError, 'DNS upstream must use authenticated encryption' unless text.match?(/\A(?:https|tls|quic|h3):\/\//i)
    raise ArgumentError, 'Unsafe DNS certificate/ECS parameter' if text.match?(/(?:skip-cert-verify|ecs(?:-override)?)=/i)
    base, suffix = text.split('#', 2)
    raise ArgumentError, 'Ambiguous DNS upstream' if base.match?(/[\s\x00-\x1f]/)
    return [base, nil, []] if suffix.nil?

    tokens = suffix.split('&', -1)
    raise ArgumentError, 'Invalid DNS upstream suffix' if tokens.empty? || tokens.any?(&:empty?)
    selectors, parameters = tokens.partition { |token| !token.include?('=') }
    raise ArgumentError, 'Ambiguous DNS upstream selector' if selectors.length > 1
    raise ArgumentError, 'Unsupported DNS upstream parameter' unless parameters.all? { |token| token.match?(SAFE_PARAMETERS) }
    [base, selectors.first, parameters]
  end

  def self.upstream(server, group = nil)
    base, selector, parameters = parts(server)
    if group.nil?
      suffix = ([selector] + parameters).compact.join('&')
      return suffix.empty? ? base : "#{base}##{suffix}"
    end

    # RULES is generated by OpenKill's split profile and is intentionally
    # replaced by the strict dedicated group. Any other selector can mean a
    # user-selected group or an egress interface; replacing it would alter
    # routing semantics, so fail with a precise reason.
    if selector && selector != group && !selector.casecmp?('RULES')
      raise ArgumentError, 'Strict DNS conflicts with an explicit upstream selector'
    end
    [base, ([group] + parameters).join('&')].join('#')
  end

  def self.strict_routed?(server, group)
    _base, selector, = parts(server)
    selector == group
  rescue ArgumentError
    false
  end
  def self.apply(value, mode, group)
    dns = value.fetch('dns')
    if mode == 'strict'
      raise ArgumentError, 'Invalid DNS group name' unless group.match?(/\A[A-Za-z0-9_-]{1,64}\z/)
      groups = value['proxy-groups'] ||= []
      raise ArgumentError, 'DNS group name conflicts with existing profile' if groups.any? { |g| g['name'] == group } || Array(value['proxies']).any? { |p| p['name'] == group }
      # Keep concrete nodes and provider-backed profiles eligible.  Nested
      # groups and implicit DIRECT are intentionally not copied into the
      # managed DNS group, because they can re-introduce a routing loop or a
      # silent clear-text fallback.  Provider names are attached with Mihomo's
      # documented `use` field and are checked again by the runtime verifier.
      nodes = Array(value['proxies']).select do |p|
        p.is_a?(Hash) && !p['name'].to_s.empty? &&
          !%w[direct reject dns].include?(p['type'].to_s.downcase) &&
          !%w[DIRECT REJECT GLOBAL COMPATIBLE PASS].include?(p['name']) &&
          !p['server'].to_s.match?(/\A(?:localhost|127\.|::1|\[::1\])/i) &&
          p['dialer-proxy'].to_s.empty?
      end.map { |p| p['name'] }.uniq
      providers = value['proxy-providers'].is_a?(Hash) ? value['proxy-providers'].keys.map(&:to_s).reject(&:empty?).uniq : []
      raise ArgumentError, 'Strict DNS requires at least one concrete proxy node or proxy provider' if nodes.empty? && providers.empty?
      managed = {'name'=>group, 'type'=>'select'}
      managed['proxies'] = nodes unless nodes.empty?
      managed['use'] = providers unless providers.empty?
      groups << managed
      # DIRECT describes the business connection, not its DNS transport.
      # Re-resolve direct exits with a domestic encrypted resolver for local
      # CDN answers, while still binding that resolver to the privacy group.
      # Never change rules or the global traffic mode to achieve DNS privacy.
      if !dns.key?('direct-nameserver') || Array(dns['direct-nameserver']).empty?
        dns['direct-nameserver'] = ['https://223.5.5.5/dns-query']
        dns['direct-nameserver-follow-policy'] = false
      end
      %w[nameserver fallback direct-nameserver].each do |key|
        next unless dns.key?(key)
        dns[key] = Array(dns[key]).map { |s| upstream(s, group) }.uniq
      end
      if dns['nameserver-policy'].is_a?(Hash)
        dns['nameserver-policy'].transform_values! { |v| Array(v).map { |s| upstream(s,group) }.uniq }
      end
      dns['respect-rules'] = false
    end
    # Direct, IP-literal, certificate-verified bootstrap avoids proxy recursion.
    dns['default-nameserver'] = BOOTSTRAP.dup
    dns['proxy-server-nameserver'] = BOOTSTRAP.dup
    if dns['proxy-server-nameserver-policy'].is_a?(Hash)
      dns['proxy-server-nameserver-policy'].transform_values! { |_v| BOOTSTRAP.dup }
    end
    value
  end
end
