#!/usr/bin/env python3
"""Phase 2C shadow context adapter and independent-intent tests.

These tests operate only on secret-free JSON fixtures and in-memory packet
descriptors.  They never source an OpenWrt init script, execute a command, or
connect to a router.  The current-intent fixture is deliberately loaded as
an independent oracle; it is not generated by the adapter during replay.
"""

from __future__ import annotations

import copy
import json
import os
import pathlib
import tempfile
import unittest

from openkill_classifier_model import backend_action, classify, classify_target
from openkill_shadow_adapter import (
    SHADOW_CONTRACT_VERSION,
    SHADOW_FIXTURE_SCHEMA,
    SHADOW_RESULTS,
    ShadowComparisonError,
    ShadowValidationError,
    adapt,
    build_context,
    normalize_packet,
    normalize_state,
    preview_target,
    shadow_compare,
    validate_intent_fixture,
    validate_state_fixture,
)


ROOT = pathlib.Path(__file__).resolve().parents[1]
STATE_FIXTURE = ROOT / "scripts/fixtures/openkill-shadow-states-v1.json"
INTENT_FIXTURE = ROOT / "scripts/fixtures/openkill-current-firewall-intent-v1.json"
ADAPTER_SOURCE = ROOT / "scripts/openkill_shadow_adapter.py"


def load_json(path):
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


class ShadowContextAdapterTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.raw_states = load_json(STATE_FIXTURE)
        cls.raw_intent = load_json(INTENT_FIXTURE)
        cls.states = validate_state_fixture(cls.raw_states)["states"]
        cls.state_by_id = {state["id"]: state for state in cls.states}
        cls.intent = validate_intent_fixture(cls.raw_intent)
        cls.cases = cls.intent["cases"]

    def test_versioned_fixture_schema_and_coverage(self):
        self.assertEqual(self.raw_states["schema"], SHADOW_FIXTURE_SCHEMA)
        self.assertEqual(self.raw_states["contract_version"], SHADOW_CONTRACT_VERSION)
        self.assertGreaterEqual(len(self.states), 12)
        self.assertTrue({
            "STATE-01-BASIC-V4",
            "STATE-02-IPV6-SOURCE-SPECIFIC",
            "STATE-03-DUAL-STACK",
            "STATE-04-NODES",
            "STATE-05-CHINA-DIRECT",
            "STATE-06-CHINA-PASS",
            "STATE-07-FAKE-IP",
            "STATE-08-LAN-ACL",
            "STATE-09-SELF-PROXY",
            "STATE-10-SELF-DIRECT",
            "STATE-11-MIHOMO-OWNER",
            "STATE-12-TPROXY",
            "STATE-13-DISABLED",
        }.issubset(self.state_by_id))
        self.assertEqual(self.raw_intent["schema"], "OPENKILL_CURRENT_INTENT_V1")
        self.assertEqual(self.raw_intent["contract_version"], SHADOW_CONTRACT_VERSION)
        self.assertGreaterEqual(len(self.cases), 60)
        families = {family: sum(case["packet"]["family"] == family for case in self.cases)
                    for family in ("IPv4", "IPv6")}
        self.assertGreaterEqual(families["IPv4"], 25)
        self.assertGreaterEqual(families["IPv6"], 25)
        self.assertGreaterEqual(sum("LAN_INGRESS" in case["coverage"] for case in self.cases), 20)
        self.assertGreaterEqual(sum("ROUTER_OUTPUT" in case["coverage"] for case in self.cases), 10)
        self.assertGreaterEqual(sum(case["category"] == "OVERLAP" for case in self.cases), 15)
        self.assertGreaterEqual(sum(case["category"] == "OWNER" for case in self.cases), 5)
        self.assertGreaterEqual(sum(case["category"] == "DNS" for case in self.cases), 6)

    def test_fixture_validation_rejects_duplicate_unknown_and_unversioned(self):
        duplicate_state = copy.deepcopy(self.raw_states)
        duplicate_state["states"].append(copy.deepcopy(duplicate_state["states"][0]))
        with self.assertRaises(ShadowValidationError):
            validate_state_fixture(duplicate_state)

        duplicate_case = copy.deepcopy(self.raw_intent)
        duplicate_case["cases"].append(copy.deepcopy(duplicate_case["cases"][0]))
        with self.assertRaises(ShadowComparisonError):
            validate_intent_fixture(duplicate_case)

        for mutation in (
            {"contract_version": 99},
            {"schema": "UNKNOWN"},
        ):
            invalid = copy.deepcopy(self.raw_intent)
            invalid.update(mutation)
            with self.assertRaises(ShadowComparisonError):
                validate_intent_fixture(invalid)

        unknown_result = copy.deepcopy(self.raw_intent)
        unknown_result["cases"][0]["independent_expected_current"]["result"] = "NOPE"
        with self.assertRaises(ShadowComparisonError):
            validate_intent_fixture(unknown_result)

        unknown_reason = copy.deepcopy(self.raw_intent)
        unknown_reason["cases"][0]["independent_expected_current"]["classifier"]["reason"] = "NOPE"
        with self.assertRaises(ShadowComparisonError):
            validate_intent_fixture(unknown_reason)

        unknown_confidence = copy.deepcopy(self.raw_intent)
        unknown_confidence["cases"][0]["independent_expected_current"]["confidence"] = "NOPE"
        with self.assertRaises(ShadowComparisonError):
            validate_intent_fixture(unknown_confidence)

        unknown_version = copy.deepcopy(self.raw_states)
        unknown_version["contract_version"] = 2
        with self.assertRaises(ShadowValidationError):
            validate_state_fixture(unknown_version)

    def test_state_canonicalization_is_order_independent(self):
        state = copy.deepcopy(self.state_by_id["STATE-04-NODES"])
        reordered = {key: copy.deepcopy(value) for key, value in reversed(list(state.items()))}
        for key, value in list(reordered.items()):
            if isinstance(value, list):
                reordered[key] = list(reversed(value))
        self.assertEqual(normalize_state(state), normalize_state(reordered))

        equivalent = copy.deepcopy(self.state_by_id["STATE-02-IPV6-SOURCE-SPECIFIC"])
        equivalent["wan6"] = ["2001:0db8:0:0:0:0:0:1/64"]
        self.assertEqual(normalize_state(equivalent)["wan6"], ["2001:db8::1"])

        # Prefixes are canonical networks; host identities are kept as hosts.
        host_state = copy.deepcopy(self.state_by_id["STATE-03-DUAL-STACK"])
        host_state["wan6"] = ["2001:db8::2/64", "2001:db8::2/128"]
        self.assertEqual(normalize_state(host_state)["wan6"], ["2001:db8::2"])

    def test_wan_hosts_and_delegated_prefixes_keep_distinct_semantics(self):
        wan_case = next(case for case in self.cases if case["id"].endswith("v6_wan_host"))
        wan_adapted = adapt(self.state_by_id[wan_case["state_id"]], wan_case["packet"])
        self.assertIn("WAN_HOST", wan_adapted["facts"]["destination_properties"])
        self.assertIn("LOCAL_DESTINATION", wan_adapted["facts"]["semantic_flags"])
        self.assertEqual(normalize_state(self.state_by_id[wan_case["state_id"]])["wan6"], [wan_case["packet"]["dst"]])

        delegated_case = next(case for case in self.cases if case["id"].endswith("v6_delegated_prefix"))
        delegated_adapted = adapt(self.state_by_id[delegated_case["state_id"]], delegated_case["packet"])
        self.assertIn("DELEGATED_PREFIX", delegated_adapted["facts"]["destination_properties"])
        self.assertNotIn("WAN_HOST", delegated_adapted["facts"]["destination_properties"])

    def test_packet_validation_and_family_safety(self):
        base = copy.deepcopy(self.cases[0]["packet"])
        invalid_family = copy.deepcopy(base)
        invalid_family["family"] = "IPv5"
        with self.assertRaises(ShadowValidationError):
            normalize_packet(invalid_family)

        invalid_protocol = copy.deepcopy(base)
        invalid_protocol["protocol"] = "SCTP"
        with self.assertRaises(ShadowValidationError):
            normalize_packet(invalid_protocol)

        invalid_icmp = copy.deepcopy(base)
        invalid_icmp["protocol"] = "ICMPv6"
        with self.assertRaises(ShadowValidationError):
            normalize_packet(invalid_icmp)

        v4_icmpv6 = copy.deepcopy(base)
        v4_icmpv6["icmpv6_type"] = "RS"
        with self.assertRaises(ShadowValidationError):
            normalize_packet(v4_icmpv6)

        wrong_self_type = copy.deepcopy(base)
        wrong_self_type["self_process"] = "yes"
        with self.assertRaises(ShadowValidationError):
            normalize_packet(wrong_self_type)

        wrong_tun = next(case for case in self.cases if case["packet"]["direction"] == "TUN_INGRESS")
        packet = copy.deepcopy(wrong_tun["packet"])
        packet["iifname"] = "other-tun"
        with self.assertRaises(ShadowValidationError):
            adapt(self.state_by_id[wrong_tun["state_id"]], packet)

        v6_generic_icmp = copy.deepcopy(base)
        v6_generic_icmp.update({"family": "IPv6", "src": "2001:db8::1", "dst": "2001:db8::2", "protocol": "ICMP"})
        self.assertEqual(normalize_packet(v6_generic_icmp)["protocol"], "ICMP")

    def test_shadow_replay_matches_independent_current_intent(self):
        results = []
        for case in self.cases:
            with self.subTest(case=case["id"]):
                state = self.state_by_id[case["state_id"]]
                result = shadow_compare(state, case["packet"], case)
                results.append(result["result"])
                self.assertIsNone(result["mismatch"], result)
                self.assertIn(result["result"], SHADOW_RESULTS)
                self.assertIn("adapted", result)
        self.assertEqual(results.count("MATCH"), 101)
        self.assertEqual(results.count("EXPECTED_CURRENT_GAP"), 7)
        self.assertEqual(results.count("INVALID_STATE"), 1)
        self.assertEqual(results.count("SEMANTIC_MISMATCH"), 0)
        self.assertEqual(results.count("UNMAPPED_STATE"), 0)
        self.assertEqual(results.count("NOT_APPLICABLE"), 0)

    def test_independent_intent_has_auditable_evidence_and_no_target(self):
        for case in self.cases:
            self.assertNotIn("target", case["independent_expected_current"])
            self.assertNotIn("expected_target", case)
            self.assertTrue(case["source_audit_id"])
            self.assertTrue(case["production_reference"])
            self.assertTrue(case["evidence"])
            expected = case["independent_expected_current"]
            if expected["result"] == "EXPECTED_CURRENT_GAP":
                self.assertIn(expected.get("known_gap"), {"BC-01", "BC-02", "BC-03", "BC-04", "BC-05", "BC-06", "BC-07"})
                self.assertIn(expected["confidence"], {"HIGH", "MEDIUM"})
            self.assertIn(expected["confidence"], {"HIGH", "MEDIUM"})

    def test_overlap_facts_are_preserved_and_target_preview_is_diagnostic(self):
        overlap = [case for case in self.cases if case["category"] == "OVERLAP"]
        target_changes = 0
        for case in overlap:
            adapted = adapt(self.state_by_id[case["state_id"]], case["packet"])
            expected_matches = set(case["independent_expected_current"]["expected_matches"])
            self.assertEqual(expected_matches, set(adapted["facts"]["semantic_flags"]), case["id"])
            current = classify(adapted["context"], profile="current", trace=True)
            preview = preview_target(adapted["context"])
            self.assertEqual(preview["current"], current.to_record())
            self.assertIsInstance(preview["changed"], bool)
            if preview["changed"]:
                target_changes += 1
        self.assertGreaterEqual(target_changes, 10)

    def test_current_undefined_mappings_are_exactly_the_known_seven(self):
        gaps = {
            case["id"]: case["independent_expected_current"].get("known_gap")
            for case in self.cases
            if case["independent_expected_current"]["result"] == "EXPECTED_CURRENT_GAP"
        }
        self.assertEqual(len(gaps), 7)
        self.assertEqual(set(gaps.values()), {"BC-01", "BC-06"})
        self.assertEqual(
            {case_id.rsplit("-", 1)[-1] for case_id in gaps if gaps[case_id] == "BC-01"},
            {"v4_user_direct", "v4_user_proxy", "v6_user_direct", "v6_user_proxy"},
        )

        candidates = {
            case["behavior_change_candidate"]["id"]
            for case in self.cases
            if case.get("behavior_change_candidate")
        }
        self.assertEqual(candidates, {"BC-01", "BC-02", "BC-03", "BC-04", "BC-05", "BC-06", "BC-07"})
        self.assertTrue(all(
            case["behavior_change_candidate"]["status"] == "PRODUCTION_NOT_APPROVED"
            for case in self.cases if case.get("behavior_change_candidate")
        ))

    def test_core_semantic_mapping_and_owner_safety(self):
        for case in self.cases:
            adapted = adapt(self.state_by_id[case["state_id"]], case["packet"])
            current = classify(adapted["context"], profile="current")
            target = classify_target(adapted["context"])
            flags = set(adapted["facts"]["semantic_flags"])
            if "DNS" in flags:
                self.assertEqual((current.reason, current.decision), ("DNS", "DNS_SPECIAL"))
            if adapted["context"]["owner"] != "OPENKILL":
                self.assertEqual((current.reason, current.decision), ("OWNER_DISABLED", "NOT_OWNED"))
                self.assertEqual((target.reason, target.decision), ("OWNER_DISABLED", "NOT_OWNED"))
            if flags & {"SELF_TRAFFIC", "TUN_INGRESS", "NODE_ENDPOINT", "LOCAL_DESTINATION", "CONTROL_PROTOCOL", "REPLY_TRAFFIC"}:
                # Current IPv6 TUN is the one audited gap; all other safety
                # reasons already return before policy in both profiles.
                if not ("TUN_INGRESS" in flags and adapted["context"]["family"] == "IPv6"):
                    self.assertEqual(target.decision, "BYPASS")

    def test_access_dns_and_backend_actions_remain_separate(self):
        access_case = next(case for case in self.cases if case["category"] == "ACCESS")
        access_adapted = adapt(self.state_by_id[access_case["state_id"]], access_case["packet"])
        self.assertIn("ACCESS_CONTROL", access_adapted["facts"]["semantic_flags"])
        self.assertNotIn("USER_DIRECT", access_adapted["facts"]["destination_properties"])
        self.assertNotIn("EXPLICIT_DIRECT", access_adapted["facts"]["semantic_flags"])

        dns_cases = [case for case in self.cases if case["category"] == "DNS"]
        self.assertGreaterEqual(len(dns_cases), 6)
        for case in dns_cases:
            adapted = adapt(self.state_by_id[case["state_id"]], case["packet"])
            self.assertIn("DNS", adapted["facts"]["semantic_flags"])
            self.assertEqual(classify(adapted["context"], profile="current").decision, "DNS_SPECIAL")

        self.assertEqual(backend_action("BYPASS", "TUN", "TCP"), "NATIVE_RETURN")
        self.assertEqual(backend_action("DIRECT", "TPROXY", "UDP"), "NATIVE_RETURN")
        self.assertEqual(backend_action("PROXY", "TUN", "UDP"), "MARK")
        self.assertEqual(backend_action("PROXY", "TPROXY", "UDP"), "MARK_TPROXY")
        self.assertEqual(backend_action("PROXY", "REDIRECT", "TCP"), "REDIRECT")
        self.assertEqual(backend_action("PROXY", "REDIRECT", "UDP"), "UNSUPPORTED_ACTION")
        self.assertEqual(backend_action("DNS_SPECIAL", "TUN", "UDP"), "DNS_REDIRECT")
        self.assertEqual(backend_action("NOT_OWNED", "TUN", "TCP"), "NOT_OWNED")
        self.assertEqual(backend_action("ACCESS_DENY", "TUN", "TCP"), "ACCESS_DENY_REQUIRED")

    def test_dns_scope_and_tun_gap_are_explicit(self):
        dns_case = next(case for case in self.cases if case["id"].endswith("v4_dns_lan"))
        state = copy.deepcopy(self.state_by_id[dns_case["state_id"]])
        packet = copy.deepcopy(dns_case["packet"])
        state["dns_scope"] = "NONE"
        adapted = adapt(state, packet)
        self.assertNotIn("DNS", adapted["facts"]["semantic_flags"])

        router_dns = next(case for case in self.cases if "ROUTER_OUTPUT" in case["coverage"] and case["category"] == "DNS")
        router_state = copy.deepcopy(self.state_by_id[router_dns["state_id"]])
        router_state["router_self_proxy"] = False
        self.assertNotIn("DNS", adapt(router_state, router_dns["packet"])["facts"]["semantic_flags"])

        tun6 = next(case for case in self.cases if case["packet"]["family"] == "IPv6" and case["packet"]["direction"] == "TUN_INGRESS")
        adapted_tun6 = adapt(self.state_by_id[tun6["state_id"]], tun6["packet"])
        current = classify(adapted_tun6["context"], profile="current")
        target = classify(adapted_tun6["context"], profile="target")
        self.assertEqual((current.reason, current.decision), ("DEFAULT_POLICY", "PROXY"))
        self.assertEqual((target.reason, target.decision), ("TUN_INGRESS", "BYPASS"))

    def test_determinism_input_order_and_side_effect_free(self):
        case = next(case for case in self.cases if case["category"] == "OVERLAP")
        state = copy.deepcopy(self.state_by_id[case["state_id"]])
        packet = copy.deepcopy(case["packet"])
        first = adapt(state, packet)
        reordered_state = {key: copy.deepcopy(value) for key, value in reversed(list(state.items()))}
        for key, value in list(reordered_state.items()):
            if isinstance(value, list):
                reordered_state[key] = list(reversed(value))
        reordered_packet = {key: packet[key] for key in reversed(list(packet))}
        second = adapt(reordered_state, reordered_packet)
        self.assertEqual(first, second)
        self.assertEqual(shadow_compare(state, packet, case)["classification"], shadow_compare(reordered_state, reordered_packet, case)["classification"])

        before_cwd = pathlib.Path.cwd()
        before_env = dict(os.environ)
        with tempfile.TemporaryDirectory() as directory:
            before_files = sorted(pathlib.Path(directory).iterdir())
            adapt(state, packet)
            shadow_compare(state, packet, case)
            self.assertEqual(before_files, sorted(pathlib.Path(directory).iterdir()))
        self.assertEqual(pathlib.Path.cwd(), before_cwd)
        self.assertEqual(dict(os.environ), before_env)

        source = ADAPTER_SOURCE.read_text(encoding="utf-8")
        for forbidden in ("subprocess", "os.system", "socket", "/etc/init.d/openkill", "luci-app-openkill"):
            self.assertNotIn(forbidden, source)

    def test_current_and_target_profiles_are_explicit(self):
        case = self.cases[0]
        context = build_context(self.state_by_id[case["state_id"]], case["packet"])
        with self.assertRaises(ValueError):
            classify(context)
        with self.assertRaises(ValueError):
            classify(context, profile="future")
        self.assertIn(preview_target(context)["current"]["status"], {"VALID", "CURRENT_UNDEFINED", "INVALID_CONFIGURATION"})

    def test_mismatch_classification_is_explicit(self):
        case = self.cases[0]
        state = self.state_by_id[case["state_id"]]

        facts_mismatch = copy.deepcopy(case)
        facts_mismatch["independent_expected_current"]["expected_matches"] = ["NODE_ENDPOINT"]
        result = shadow_compare(state, case["packet"], facts_mismatch)
        self.assertEqual(result["result"], "SEMANTIC_MISMATCH")
        self.assertEqual(result["mismatch"]["type"], "ADAPTER_DEFECT")

        classifier_mismatch = copy.deepcopy(case)
        classifier_mismatch["independent_expected_current"]["classifier"]["reason"] = "DEFAULT_POLICY"
        result = shadow_compare(state, case["packet"], classifier_mismatch)
        self.assertEqual(result["result"], "SEMANTIC_MISMATCH")
        self.assertEqual(result["mismatch"]["type"], "CLASSIFIER_CONTRACT_DEFECT")

        gap_mismatch = copy.deepcopy(case)
        gap_mismatch["independent_expected_current"]["result"] = "UNMAPPED_STATE"
        gap_mismatch["independent_expected_current"]["classifier"]["reason"] = "DEFAULT_POLICY"
        result = shadow_compare(state, case["packet"], gap_mismatch)
        self.assertEqual(result["result"], "SEMANTIC_MISMATCH")
        self.assertEqual(result["mismatch"]["type"], "PRODUCTION_AMBIGUITY")


if __name__ == "__main__":
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(ShadowContextAdapterTests)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    raise SystemExit(0 if result.wasSuccessful() else 1)
